Repository lbl-srg/modelica-buildings, pull requests merged in 2020-11, with the labels that each got.

#2195 Enable simulation test of OBC package with OpenModelica
  .travis.yml
  Buildings/Resources/Scripts/travis/Makefile
  Buildings/Resources/Scripts/travis/omc/testOpenModelica.sh
Labels: OpenBuildingControl

#2222 Reformulated model for #2221
  Buildings/ThermalZones/EnergyPlus/BaseClasses/FMUInputVariableClass.mo
  Buildings/ThermalZones/EnergyPlus/BaseClasses/FMUOutputVariableClass.mo
  Buildings/ThermalZones/EnergyPlus/ThermalZone.mo
  Buildings/ThermalZones/EnergyPlus/package.mo
Labels: spawn

#2025 Issue2024 ashrae2006 sequence
  Buildings/Examples/DualFanDualDuct/ClosedLoop.mo
  Buildings/Examples/DualFanDualDuct/Controls/CoolingCoilTemperatureSetpoint.mo
  Buildings/Examples/DualFanDualDuct/Controls/MixedAirTemperatureSetpoint.mo
  Buildings/Examples/DualFanDualDuct/Controls/package.order
  Buildings/Examples/ScalableBenchmarks/BuildingVAV/Examples/OneFloor_OneZone.mo
  Buildings/Examples/VAVReheat/ASHRAE2006.mo
  Buildings/Examples/VAVReheat/BaseClasses/PartialOpenLoop.mo
  Buildings/Examples/VAVReheat/Controls/CoolingCoilTemperatureSetpoint.mo
  Buildings/Examples/VAVReheat/Controls/Economizer.mo
  Buildings/Examples/VAVReheat/Controls/EconomizerTemperatureControl.mo
  Buildings/Examples/VAVReheat/Controls/Examples/SupplyAirTemperature.mo
  Buildings/Examples/VAVReheat/Controls/Examples/package.order
  Buildings/Examples/VAVReheat/Controls/ModeSelector.mo
  Buildings/Examples/VAVReheat/Controls/SupplyAirTemperature.mo
  Buildings/Examples/VAVReheat/Controls/SupplyAirTemperatureSetpoint.mo
  Buildings/Examples/VAVReheat/Controls/package.order
  Buildings/Examples/VAVReheat/Guideline36.mo
  Buildings/Fluid/Actuators/BaseClasses/PartialDamperExponential.mo
  Buildings/Fluid/Examples/Performance/Example2.mo
  Buildings/Fluid/MixingVolumes/Validation/TraceSubstanceConservationDynamicBalance.mo
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Examples_DualFanDualDuct_ClosedLoop.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Examples_ScalableBenchmarks_BuildingVAV_Examples_OneFloor_OneZone.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Examples_ScalableBenchmarks_BuildingVAV_Examples_TwoFloor_TwoZone.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Examples_VAVReheat_ASHRAE2006.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Examples_VAVReheat_Controls_Examples_SupplyAirTemperature.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Examples_VAVReheat_Guideline36.txt
  Buildings/Resources/Scripts/Dymola/Examples/DualFanDualDuct/ClosedLoop.mos
  Buildings/Resources/Scripts/Dymola/Examples/ScalableBenchmarks/BuildingVAV/Examples/OneFloor_OneZone.mos
  Buildings/Resources/Scripts/Dymola/Examples/VAVReheat/ASHRAE2006.mos
  Buildings/Resources/Scripts/Dymola/Examples/VAVReheat/Controls/Examples/SupplyAirTemperature.mos
  Buildings/Resources/Scripts/Dymola/Examples/VAVReheat/Guideline36.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Examples.DualFanDualDuct.ClosedLoop.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Examples.ScalableBenchmarks.BuildingVAV.Examples.OneFloor_OneZone.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Examples.VAVReheat.ASHRAE2006.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Examples.VAVReheat.Controls.Examples.SupplyAirTemperature.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Examples.VAVReheat.Guideline36.mos
  Buildings/package.mo
Labels: OpenBuildingControl

#2241 Enabled omc tests
  .travis.yml
Labels: OpenModelica

#2255 Issue2204 gmt mbl ets cooling
  Buildings/Experimental/DHC/EnergyTransferStations/Cooling/CoolingDirectControlledReturn.mo
  Buildings/Experimental/DHC/EnergyTransferStations/Cooling/CoolingDirectUncontrolled.mo
  Buildings/Experimental/DHC/EnergyTransferStations/Cooling/CoolingIndirect.mo
  Buildings/Experimental/DHC/EnergyTransferStations/Cooling/Examples/CoolingDirectControlledReturn.mo
  Buildings/Experimental/DHC/EnergyTransferStations/Cooling/Examples/CoolingDirectUncontrolled.mo
  Buildings/Experimental/DHC/EnergyTransferStations/Cooling/Examples/CoolingIndirectClosedBuildingLoop.mo
  Buildings/Experimental/DHC/EnergyTransferStations/Cooling/Examples/CoolingIndirectOpenLoops.mo
  Buildings/Experimental/DHC/EnergyTransferStations/Cooling/Examples/package.order
  Buildings/Experimental/DHC/EnergyTransferStations/Cooling/package.order
  Buildings/Resources/Images/Experimental/DHC/EnergyTransferStations/CoolingDirectControlledReturn.PNG
  Buildings/Resources/Images/Experimental/DHC/EnergyTransferStations/CoolingDirectControlledReturn.svg
  Buildings/Resources/Images/Experimental/DHC/EnergyTransferStations/CoolingDirectUncontrolled.PNG
  Buildings/Resources/Images/Experimental/DHC/EnergyTransferStations/CoolingDirectUncontrolled.svg
  Buildings/Resources/Images/Experimental/DHC/EnergyTransferStations/CoolingIndirect.png
  Buildings/Resources/Images/Experimental/DHC/EnergyTransferStations/CoolingIndirect.svg
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_EnergyTransferStations_Cooling_Examples_CoolingDirectControlledReturn.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_EnergyTransferStations_Cooling_Examples_CoolingDirectUncontrolled.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_EnergyTransferStations_Cooling_Examples_CoolingIndirectClosedBuildingLoop.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_EnergyTransferStations_Cooling_Examples_CoolingIndirectOpenLoops.txt
  Buildings/Resources/Scripts/Dymola/Experimental/DHC/EnergyTransferStations/Cooling/Examples/CoolingDirectControlledReturn.mos
  Buildings/Resources/Scripts/Dymola/Experimental/DHC/EnergyTransferStations/Cooling/Examples/CoolingDirectUncontrolled.mos
  Buildings/Resources/Scripts/Dymola/Experimental/DHC/EnergyTransferStations/Cooling/Examples/CoolingIndirectClosedBuildingLoop.mos
  Buildings/Resources/Scripts/Dymola/Experimental/DHC/EnergyTransferStations/Cooling/Examples/CoolingIndirectOpenLoops.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Experimental.DHC.EnergyTransferStations.Cooling.Examples.CoolingDirectControlledReturn.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Experimental.DHC.EnergyTransferStations.Cooling.Examples.CoolingDirectUncontrolled.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Experimental.DHC.EnergyTransferStations.Cooling.Examples.CoolingIndirectClosedBuildingLoop.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Experimental.DHC.EnergyTransferStations.Cooling.Examples.CoolingIndirectOpenLoops.mos
Labels: URBANopt

#2244 Removed dependency on Modelica.SIunits for #2243
  Buildings/Controls/OBC/CDL/Continuous/MovingMean.mo
  Buildings/Controls/OBC/CDL/Continuous/PID.mo
  Buildings/Controls/OBC/CDL/Continuous/PIDWithReset.mo
  Buildings/Controls/OBC/CDL/Continuous/SlewRateLimiter.mo
  Buildings/Controls/OBC/CDL/Continuous/Sources/CalendarTime.mo
  Buildings/Controls/OBC/CDL/Continuous/Sources/Pulse.mo
  Buildings/Controls/OBC/CDL/Continuous/Sources/Ramp.mo
  Buildings/Controls/OBC/CDL/Continuous/Sources/Sine.mo
  Buildings/Controls/OBC/CDL/Continuous/Sources/TimeTable.mo
  Buildings/Controls/OBC/CDL/Discrete/DayType.mo
  Buildings/Controls/OBC/CDL/Discrete/FirstOrderHold.mo
  Buildings/Controls/OBC/CDL/Discrete/Sampler.mo
  Buildings/Controls/OBC/CDL/Discrete/UnitDelay.mo
  Buildings/Controls/OBC/CDL/Discrete/ZeroOrderHold.mo
  Buildings/Controls/OBC/CDL/Integers/Sources/Pulse.mo
  Buildings/Controls/OBC/CDL/Integers/Sources/TimeTable.mo
  Buildings/Controls/OBC/CDL/Logical/Sources/Pulse.mo
  Buildings/Controls/OBC/CDL/Logical/Sources/SampleTrigger.mo
  Buildings/Controls/OBC/CDL/Logical/Sources/TimeTable.mo
  Buildings/Controls/OBC/CDL/Logical/Timer.mo
  Buildings/Controls/OBC/CDL/Logical/TimerAccumulating.mo
  Buildings/Controls/OBC/CDL/Logical/TriggeredTrapezoid.mo
  Buildings/Controls/OBC/CDL/Logical/TrueDelay.mo
  Buildings/Controls/OBC/CDL/Logical/TrueFalseHold.mo
  Buildings/Controls/OBC/CDL/Logical/TrueHoldWithReset.mo
  Buildings/Controls/OBC/CDL/Psychrometrics/DewPoint_TDryBulPhi.mo
  Buildings/Controls/OBC/CDL/Psychrometrics/SpecificEnthalpy_TDryBulPhi.mo
  Buildings/Controls/OBC/CDL/Psychrometrics/WetBulb_TDryBulPhi.mo
  Buildings/Controls/OBC/CDL/SetPoints/SupplyReturnTemperatureReset.mo
  Buildings/Controls/OBC/CDL/Utilities/SunRiseSet.mo
  Buildings/package.mo
Labels: OpenBuildingControl
