Repository lbl-srg/modelica-buildings, pull requests merged in 2020-10, with the labels that each got.

#2150 Refactored TimeSeries model in staging branch issue1437 to allow heating-only or cooling-only modeling
  Buildings/Applications/DHC/Loads/Examples/BaseClasses/BuildingTimeSeries.mo
  Buildings/Applications/DHC/Loads/Examples/CouplingTimeSeries.mo
  Buildings/Applications/DHC/Loads/Examples/CouplingTimeSeriesSingleLoop.mo
  Buildings/Applications/DHC/Loads/Examples/package.order
  Buildings/Applications/DHC/Loads/Validation/BaseClasses/FanCoil2PipeCooling.mo
  Buildings/Applications/DHC/Loads/Validation/BaseClasses/FanCoil2PipeHeating.mo
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Applications_DHC_Loads_Controls_Validation_MixingValveControl.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Applications_DHC_Loads_Examples_CouplingTimeSeries.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Applications_DHC_Loads_Examples_CouplingTimeSeriesSingleLoop.txt
  Buildings/Resources/Scripts/BuildingsPy/conf.json
  Buildings/Resources/Scripts/Dymola/Applications/DHC/Loads/Examples/CouplingTimeSeriesSingleLoop.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Applications.DHC.Loads.Examples.CouplingTimeSeriesSingleLoop.mos
Labels: URBANopt

#2173 Removed default value of maximum/minimum airflow setpoints of the terminal box control
  Buildings/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/Controller.mo
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Examples_VAVReheat_Guideline36.txt
  Buildings/package.mo
Labels: non-backward compatible

#2183 Issue2182 pid
  Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/Economizers/Subsequences/Modulation.mo
  Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/ExhaustDamper.mo
  Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/ReturnFanDirectPressure.mo
  Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/SupplyFan.mo
  Buildings/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/Reheat/DamperValves.mo
  Buildings/Controls/OBC/CDL/Continuous/PID.mo
  Buildings/Controls/OBC/CDL/Continuous/PIDWithReset.mo
  Buildings/Controls/OBC/CDL/Continuous/Validation/PID.mo
  Buildings/Controls/OBC/CDL/Continuous/Validation/PIDScale.mo
  Buildings/Controls/OBC/CDL/Continuous/Validation/PIDWithReset.mo
  Buildings/Controls/OBC/CDL/Continuous/Validation/PIDWithResetScale.mo
  Buildings/Controls/OBC/CDL/Continuous/Validation/package.order
  Buildings/Examples/DualFanDualDuct/Controls/RoomMixingBox.mo
  Buildings/Obsolete/Controls/OBC/CDL/Continuous/LimPID.mo
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Controls_OBC_CDL_Continuous_Validation_PID.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Controls_OBC_CDL_Continuous_Validation_PIDInitialState.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Controls_OBC_CDL_Continuous_Validation_PIDScale.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Controls_OBC_CDL_Continuous_Validation_PIDWithReset.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Controls_OBC_CDL_Continuous_Validation_PIDWithResetScale.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Examples_DualFanDualDuct_ClosedLoop.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Examples_VAVReheat_Guideline36.txt
  Buildings/Resources/Scripts/Dymola/Controls/OBC/CDL/Continuous/Validation/PID.mos
  Buildings/Resources/Scripts/Dymola/Controls/OBC/CDL/Continuous/Validation/PIDScale.mos
  Buildings/Resources/Scripts/Dymola/Controls/OBC/CDL/Continuous/Validation/PIDWithResetScale.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Controls.OBC.CDL.Continuous.Validation.PID.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Controls.OBC.CDL.Continuous.Validation.PIDScale.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Controls.OBC.CDL.Continuous.Validation.PIDWithResetScale.mos
  Buildings/package.mo
Labels: OpenBuildingControl

#2208 Issue1954 internal heat gains
  Buildings/Resources/ReferenceResults/Dymola/Buildings_ThermalZones_EnergyPlus_Validation_ThermalZone_InternalGain.txt
  Buildings/Resources/Scripts/Dymola/ThermalZones/EnergyPlus/Validation/ThermalZone/InternalGain.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.ThermalZones.EnergyPlus.Validation.ThermalZone.InternalGain.mos
  Buildings/ThermalZones/EnergyPlus/ThermalZone.mo
  Buildings/ThermalZones/EnergyPlus/Validation/ThermalZone/InternalGain.mo
  Buildings/ThermalZones/EnergyPlus/Validation/ThermalZone/package.order
Labels: spawn
