Repository lbl-srg/modelica-buildings, pull requests merged in 2020-12, with the labels that each got.

#2281 Corrected typos in connector comment
  Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/ExhaustDamper.mo
  Buildings/Controls/OBC/CDL/Logical/And3.mo
  Buildings/Controls/OBC/CDL/Logical/Or3.mo
Labels: OpenBuildingControl

#2270 Issue2204 2264 cooling plant
  Buildings/Experimental/DHC/CentralPlants/Cooling/Examples/CoolingPlantOpenLoop.mo
  Buildings/Experimental/DHC/CentralPlants/Cooling/Examples/package.order
  Buildings/Experimental/DHC/CentralPlants/Cooling/Plant.mo
  Buildings/Experimental/DHC/CentralPlants/Cooling/package.order
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_CentralPlants_Cooling_Examples_CoolingPlantOpenLoop.txt
  Buildings/Resources/Scripts/Dymola/Experimental/DHC/CentralPlants/Cooling/Examples/CoolingPlantOpenLoop.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Experimental.DHC.CentralPlants.Cooling.Examples.CoolingPlantOpenLoop.mos
Labels: URBANopt

#2288 Reformulated to avoid 'when not initial()'
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_Loads_Examples_CouplingSpawnZ6.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_ThermalZones_EnergyPlus_Validation_Actuator_LightsControl.txt
  Buildings/ThermalZones/EnergyPlus/BaseClasses/FMUZoneAdapter.mo
  Buildings/ThermalZones/EnergyPlus/OutputVariable.mo
Labels: spawn

#2306 Issue2204 2201 loads time series
  Buildings/Experimental/DHC/Loads/Examples/BaseClasses/BuildingTimeSeries.mo
  Buildings/Experimental/DHC/Loads/Examples/CouplingTimeSeriesSingleLoop.mo
  Buildings/Experimental/DHC/Loads/Examples/CouplingTimeSeries_Hospital.mo
  Buildings/Experimental/DHC/Loads/Examples/CouplingTimeSeries_MediumOffice.mo
  Buildings/Experimental/DHC/Loads/Examples/CouplingTimeSeries_PrimarySchool.mo
  Buildings/Experimental/DHC/Loads/Examples/CouplingTimeSeries_Residential.mo
  Buildings/Experimental/DHC/Loads/Examples/package.order
  Buildings/Resources/Data/Experimental/DHC/Loads/Examples/MediumOffice-90.1-2010-5A.mos
  Buildings/Resources/Data/Experimental/DHC/Loads/Examples/primaryschool-3C-2013.mos
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_Loads_Examples_CouplingTimeSeriesSingleLoop.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_Loads_Examples_CouplingTimeSeries_Hospital.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_Loads_Examples_CouplingTimeSeries_MediumOffice.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_Loads_Examples_CouplingTimeSeries_PrimarySchool.txt
  Buildings/Resources/ReferenceResults/Dymola/Buildings_Experimental_DHC_Loads_Examples_CouplingTimeSeries_Residential.txt
  Buildings/Resources/Scripts/Dymola/Experimental/DHC/Loads/Examples/CouplingTimeSeriesSingleLoop.mos
  Buildings/Resources/Scripts/Dymola/Experimental/DHC/Loads/Examples/CouplingTimeSeries_Hospital.mos
  Buildings/Resources/Scripts/Dymola/Experimental/DHC/Loads/Examples/CouplingTimeSeries_MediumOffice.mos
  Buildings/Resources/Scripts/Dymola/Experimental/DHC/Loads/Examples/CouplingTimeSeries_PrimarySchool.mos
  Buildings/Resources/Scripts/Dymola/Experimental/DHC/Loads/Examples/CouplingTimeSeries_Residential.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Experimental.DHC.Loads.Examples.CouplingTimeSeriesSingleLoop.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Experimental.DHC.Loads.Examples.CouplingTimeSeries_Hospital.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Experimental.DHC.Loads.Examples.CouplingTimeSeries_MediumOffice.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Experimental.DHC.Loads.Examples.CouplingTimeSeries_PrimarySchool.mos
  Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Experimental.DHC.Loads.Examples.CouplingTimeSeries_Residential.mos
Labels: URBANopt

#2279 Added OBC naming convention
  Buildings/Controls/OBC/UnitConversions/From_Btu.mo
  Buildings/Controls/OBC/UnitConversions/From_quad.mo
  Buildings/Controls/OBC/UnitConversions/To_Btu.mo
  Buildings/Controls/OBC/UnitConversions/To_quad.mo
  Buildings/Controls/OBC/UnitConversions/Validation/From_Btu.mo
  Buildings/Controls/OBC/UnitConversions/Validation/From_quad.mo
  Buildings/Controls/OBC/UnitConversions/Validation/To_Btu.mo
  Buildings/Controls/OBC/UnitConversions/Validation/To_quad.mo
  Buildings/Controls/OBC/UsersGuide/Conventions.mo
  Buildings/Controls/OBC/UsersGuide/package.mo
  Buildings/Controls/OBC/UsersGuide/package.order
  Buildings/Controls/OBC/package.order
  Buildings/Resources/src/Controls/OBC/UnitConversions/unit_converters.py
  Buildings/package.mo
Labels: OpenBuildingControl

#2307 Corrected quantity attribute
  Buildings/package.mo
Labels: OpenBuildingControl
